name: CI

on:
  push:
    branches: ["master", "main"]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build test image
        run: docker build -f Dockerfile.test -t connect4-ai-test .
      - name: Run C and Python tests
        run: docker run --rm connect4-ai-test
