name: CI

on:
  push:
    branches: ["master", "main"]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y clang make
      - name: Install Python dependencies
        run: pip install -r requirements-dev.txt
      - name: Run automated tests
        run: scripts/run_tests.sh
